image: gitpod/workspace-dotnet

tasks:
  - name: Setup C++ Environment
    init: bash ./cpp/setup-gitpod.sh
    command: bash ./cpp/run-tests-gitpod.sh
  - name: Setup .NET Environment  
    init: |
      cd csharp
      dotnet restore Platform.Interfaces.sln
      dotnet build Platform.Interfaces.sln
    command: echo ".NET 8 SDK is ready for development"
