image: gitpod/workspace-dotnet

tasks:
  - name: Setup C++ Environment
    init: sh ./cpp/setup-gitpod.sh
    command: sh ./cpp/run-tests-gitpod.sh
  - name: Setup .NET Environment  
    init: |
      cd csharp
      dotnet restore Platform.Abstractions.sln
      dotnet build Platform.Abstractions.sln
    command: echo ".NET 8 SDK is ready for development"
