//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


[assembly: System.Reflection.AssemblyConfigurationAttribute("Debug")]
[assembly: System.Reflection.AssemblyCopyrightAttribute("Konstantin Diachenko")]
[assembly: System.Reflection.AssemblyDescriptionAttribute("LinksPlatform\'s Platform.Interfaces Class Library")]
[assembly: System.Reflection.AssemblyFileVersionAttribute("0.2.0.0")]
[assembly: System.Reflection.AssemblyInformationalVersionAttribute("0.2.0+047e0b27e6aa0cbb420b600b3d226deccd64eb47")]
[assembly: System.Reflection.AssemblyTitleAttribute("Platform.Interfaces")]
[assembly: System.Reflection.AssemblyVersionAttribute("0.2.0.0")]

// Generated by the MSBuild WriteCodeFragment class.

