on:
  release:
    types: [published]
        
jobs:
  push_to_conan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
      - name: Publish to the official conan repository
        uses: Minimonium/conan-request-action@master
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          packageName: "platform.interfaces"
      - name: Publish to the linksplatform conan repository
        uses: Minimonium/conan-request-action@master
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          packageName: "platform.interfaces"
          upstreamOwner: 'linksplatform'
