name: Deploy new cpp version

on:
  push:
    branches: main 
    paths:
      - 'cpp/**/*.nuspec'

jobs:
  main:
    uses: linksplatform/Workflows/.github/workflows/cpp-deploy.yml@main
    secrets:
        NUGET_TOKEN: ${{ secrets.NUGET_TOKEN }}
