name: Test cpp

on:
  push:
    branches:
      - 'main'
    paths:
      - 'cpp/**'
  pull_request:
    types:
      - edited
    branches:
      - 'main'
    paths:
      - 'cpp/**'
      
jobs:
  main:
    uses: linksplatform/Workflows/.github/workflows/cpp-test.yml@main
