name: cpp

on:
  push:
    branches: main
    paths:
      - 'cpp/**'
      - '.github/workflows/cpp.yml'

jobs:
  main:
    uses: linksplatform/Workflows/.github/workflows/cpp.yml@main
    secrets:
#         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        NUGETTOKEN: ${{ secrets.NUGET_TOKEN }}
