name: cpp

on:
  push:
    branches: main
    paths:
      - 'cpp/**'
      - '.github/workflows/cpp.yml'

env:
  NUGETTOKEN: ${{ secrets.NUGET_TOKEN }}
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  SCRIPTS_BASE_URL: https://raw.githubusercontent.com/linksplatform/Scripts/main/MultiProjectRepository

defaults:
  run:
    working-directory: cpp

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
        with:
          submodules: true
      - name: Setup clang
        uses: egor-tensin/setup-clang@v1
        with:
          version: 13
          platform: x64
      - name: Install conan
        run: pip install conan
      - name: Setup conan
        run: |
          conan profile new linksplatform --detect
          conan profile update settings.compiler=clang linksplatform
          conan profile update settings.compiler.version=13 linksplatform
          conan profile update settings.compiler.libcxx=libstdc++11 linksplatform
          conan profile update env.CXX=clang++ linksplatform
          conan profile show linksplatform
      - name: Instll conan packages
        run: |
          if [ -f "install-local-conan-dependencies.sh" ]; then
              echo "install-local-conan-dependencies.sh exists."
              chmod +x ./install-local-conan-dependencies.sh
              ./install-local-conan-dependencies.sh
          fi
      - name: Test and scan-build
        run: |
          CXX=clang++
          cmake_flags="-DCMAKE_BUILD_TYPE=Release -DCMAKE_CXX_COMPILER=clang++ -DLINKS_PLATFORM_TESTS=TRUE"
          cmake_build_dir="build"
          mkdir $cmake_build_dir && cd $cmake_build_dir
          conan install .. -pr=linksplatform --build=missing
          cmake .. "$cmake_flags"
          cmake --build .
          ls
  pushToNuget:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - uses: actions/checkout@v1
        with:
          submodules: true
      - name: Read package information
        run: |
          export REPOSITORY_NAME=$(basename ${{ github.repository }})
          wget "$SCRIPTS_BASE_URL/read_cpp_package_info.sh"
          bash ./read_cpp_package_info.sh
      - name: Publish NuGet package
        run: |
          export REPOSITORY_NAME=$(basename ${{ github.repository }})
          wget "$SCRIPTS_BASE_URL/push-cpp-nuget.sh"
          bash ./push-cpp-nuget.sh
  publishRelease:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - uses: actions/checkout@v1
        with:
          submodules: true
      - name: Read project information
        run: |
          export REPOSITORY_NAME=$(basename ${{ github.repository }})
          wget "$SCRIPTS_BASE_URL/read_cpp_package_info.sh"
          bash ./read_cpp_package_info.sh
      - name: Publish release
        run: |
          export REPOSITORY_NAME=$(basename ${{ github.repository }})
          wget "$SCRIPTS_BASE_URL/publish-release.sh"
          chmod +x ./publish-release.sh
          wget "$SCRIPTS_BASE_URL/publish-cpp-release.sh"
          bash ./publish-cpp-release.sh
  getConanPackageInfo:
    runs-on: ubuntu-latest
    outputs: 
      packageName: ${{steps.getPackageName.packageName}}
      newPackageVersion: ${{steps.getNewPackageVersion.newPackageVersion}}
    steps:
      - name: Get package name
        id: getPackageName
        run: |
          REPOSITORY_NAME=$(basename ${{ github.repository }})
          PACKAGE_NAME="platform.${REPOSITORY_NAME@L}"
          echo "packageName=${PACKAGE_NAME}" >> $GITHUB_OUTPUT
      - name: Get new conan package version
        id: getNewPackageVersion
        run: |
          export REPOSITORY_NAME=$(basename ${{ github.repository }})
          wget "$SCRIPTS_BASE_URL/read_cpp_package_info.sh"
          bash ./read_cpp_package_info.sh
          echo "newPackageVersion=${CPP_PACKAGE_VERSION}" >> $GITHUB_OUTPUT
  pushToConan:
    runs-on: ubuntu-latest
    needs: getConanPackageInfo
    steps:
      - uses: Minimonium/conan-request-action@master
      - name: Publish to the official conan repository
        with:
          token: ${{ secrets.PERSONAL_TOKEN }}
          packageName: ${{needs.getConanPackageInfo.outputs.packageName}}
      - uses: Minimonium/conan-request-action@master
      - name: Publish to the linksplatform conan repository
        with:
          token: ${{ secrets.PERSONAL_TOKEN }}
          packageName: ${{needs.getConanPackageInfo.outputs.packageName}}
          upstreamOwner: 'linksplatform'
  updateConanDependants:
    runs-on: ubuntu-latest
    needs: [pushToConan, getConanPackageInfo]
    outputs:
      newCppPackageVersion: ${{ needs.getConanPackageInfo.outputs.newPackageVersion }}
    steps:
      - name: Update conan dependants in organization
        uses: FreePhoenix888/update-conan-dependants-in-organization-action@v0.0.1-alpha
        with:
          token: ${{ secrets.PERSONAL_TOKEN }}
          organizationName: 'linksplatform'
          conanFilePath: 'cpp/conanfile.txt'
          commitMessageTemplate: 'Update ${{needs.getConanPackageInfo.outputs.packageName}} dependency from {PREVIOUS_VERSION} to ${{needs.getConanPackageInfo.outputs.newPackageVersion}}'
          sourceBranchName: 'main'
          destinationBranchName: 'main'
          conanFileReplaceableRegex: "${{needs.getConanPackageInfo.outputs.packageName}}/\\(?<PREVIOUS_VERSION>\\d\\.\\d\\.\\d\\)"
          conanFileReplacement: '${{needs.getConanPackageInfo.outputs.packageName}}/${{need.getConanPackageInfo.outputs.newCppPackageVersion}}'
          shouldOpenPullRequest: 'false'
