on:
  workflow_call:
    inputs:
      github_ref:
        required: true
        type: string
        
jobs:
  reusable_workflow_job:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/labeler@v4
      echo: "Github ref: ${{inputs.github_ref}}"
