on:
  workflow_call:
    inputs:
      github_ref:
        required: true
        type: string
        
jobs:
  reusable_workflow_job:
    runs-on: ubuntu-latest
    steps:
      - name: "Test"
        run: |
          echo ${{inputs.github_ref}}
