on:
  push:
    branches: main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Test
      run: | 
        echo ${{event.commit.modified}};
        echo ${{contains(event.commit.modified, "Interfaces/cpp/setup-gitpod.sh")}};
