on:
  push:
    branches: main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Test
      run: | 
        echo ${{toJSON(github.event)}};
        echo ${{github.event.commits.modified}};
        echo ${{contains(github.event.commits.modified, 'Interfaces/cpp/setup-gitpod.sh')}};
