on:
  release:
    types: [published]

jobs:
  call-workflow:
    uses: linksplatform/Scripts/.github/workflows/get-cpp-conan-package-info.yml@c866b082c36961c1417a23099b9f21678eeb83e6
    with:
      github_ref: ${{github.ref}}

# jobs:
#   publish:
#     if: startsWith(github.ref, 'refs/tags/cpp')
#     runs-on: ubuntu-latest
#     steps:
#       - name: Publish to the official conan repository
#         uses: Minimonium/conan-request-action@master
#         with:
#           token: ${{ secrets.PERSONAL_TOKEN }}
#           packageName: ${{needs.getConanPackageInfo.outputs.packageName}}
#       - name: Publish to the linksplatform conan repository
#         uses: Minimonium/conan-request-action@master
#         with:
#           token: ${{ secrets.PERSONAL_TOKEN }}
#           packageName: ${{needs.getConanPackageInfo.outputs.packageName}}
#           upstreamOwner: 'linksplatform'
